backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "content"
    label: "Contenu du site"
    files:
      - file: "content.json"
        label: "Configuration Générale & Pages"
        name: "info"
        fields:
          # --- Entête et Réseaux ---
          - { label: "Nom du Pays (En-tête & Titre)", name: "country_name", widget: "string" }
          - { label: "Nom du Serveur NationsGlory", name: "server_name", widget: "string" }
          - { label: "Slogan / Citation", name: "slogan", widget: "string" }
          - { label: "Texte de bienvenue (Accueil)", name: "description", widget: "text" }
          - { label: "Lien de l'invitation Discord", name: "discord_link", widget: "string" }
          
          # --- Gestion Totale des Onglets ---
          - label: "Gestion des Onglets / Pages"
            name: "tabs"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - { label: "Titre de l'onglet (ex: Lore, Gouvernement...)", name: "title", widget: "string" }
              - { label: "Identifiant unique (en minuscules, ex: lore)", name: "id", widget: "string" }
              - { label: "Contenu de la page (Texte ou HTML)", name: "content", widget: "markdown" }
