backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "content"
    label: "Contenu du site"
    files:
      - file: "content.json"
        label: "Informations Principales"
        name: "info"
        fields:
          - label: "Nom du Pays"
            name: "country_name"
            widget: "string"
          - label: "Slogan"
            name: "slogan"
            widget: "string"
          - label: "Description / Lore"
            name: "description"
            widget: "text"
          - label: "Lien Discord"
            name: "discord_link"
            widget: "string"
